#pragma once
#include "DrivingMode.h"

#define DMF					DrivingMode::DRIVING_STYLE_FLAGS 
#define DEFAULT				DMF::DRIVE_AROUND_EMPTY_VEHICLES | DMF::DRIVE_AROUND_OBJECTS | DMF::STOP_AT_TRAFFIC_LIGHTS | DMF::USE_BLINKERS
#define DUAL_STOP			DMF::FOLLOWING_TRAFFICS | DMF::YIELD_TO_CROSSING_PEDS
#define DUAL_AVOID			DMF::DRIVE_AROUND_VEHICLES | DMF::DRIVE_AROUND_PEDS
#define LANE_SELECT_1		0
#define LANE_SELECT_2		DMF::ALLOW_LANE_CHANEING
#define LANE_SELECT_3		DMF::ALLOW_LANE_CHANEING | DMF::TAKE_SHORTEST_PATH | DMF::ALLOW_GOING_WRONG_WAY

#define STRICT_1			DEFAULT | DUAL_STOP | LANE_SELECT_1
#define STRICT_2			DEFAULT | DUAL_STOP | LANE_SELECT_2
#define LOOSE_1				DEFAULT | DUAL_STOP | DUAL_AVOID | LANE_SELECT_2
#define LOOSE_2				DEFAULT | DUAL_STOP | DUAL_AVOID | LANE_SELECT_3